title: Hunter Pankey
subtitle: A blog about gamedev and maybe some other stuff
description: >- # this means to ignore newlines until "baseurl:"
  Unity is great and the asset store is full of good stuff to help a solo dev make some progress. But documentation is frequently terrible, so here's a blog about the stuff I use and how to make it work, but like, for real.

url: "https://hunterpankey.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  # - text: Gallery
  #   url: /gallery
  # - text: Shop
  #   url: /shop
  - text: Contact
    url: /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Hunter Pankey
author_bio: I kind of make games when I'm not trying to convince people to stop emailing documents to each other. It's uphill work.
author_email: "lll@lll.com"
author_location: New York, NY, USA
author_website_url: "https://hunterpankey.com"
typewrite-text: Let's make some games!
hero_cover_img: hero_cover.png # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  # - company_name: Company
  #   company_logo: company_logo.png
  #   company_url: https://company_domain.com
  #   designation: Software Engineer
  #   description: Worked on various Products and Projects
  #   visibility: true

# Education
author_education_details:
  - college_logo: gatech.png
    college_name: Georgia Tech
    college_url: https://gatech.edu
    college_degree: BS, CS
    description: Bachelor of Science in Computer Science
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: projects/fallguysstats.png
    project_title: Fall Guys Stats
    project_description: Windows application to track statistics in Fall Guys
    project_url: https://github.com/ShootMe/FallGuysStats
    visibility: true
  - project_thumbnail: projects/rocksniffergui.PNG
    project_title: RockSniffer GUI
    project_description: Windows application to track statistics in RockSmith
    project_url: https://github.com/hunterpankey/RockSnifferGui
    visibility: true

# social links
# twitter_username: johndoe
github_username: hunterpankey
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  - scope:
      path: "assets/**"
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md

destination: ./build
